# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptoasset',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Url', models.CharField(blank=True, max_length=100)),
                ('ImageUrl', models.CharField(blank=True, max_length=100)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('CoinName', models.CharField(blank=True, max_length=100)),
                ('FullName', models.CharField(blank=True, max_length=100)),
                ('Algorithm', models.CharField(blank=True, max_length=100)),
                ('ProofType', models.CharField(blank=True, max_length=100)),
                ('FullyPremined', models.CharField(blank=True, max_length=100)),
                ('TotalCoinSypply', models.CharField(blank=True, max_length=100)),
                ('PreminedValue', models.CharField(blank=True, max_length=100)),
                ('TotalCoinsFreeFloat', models.CharField(blank=True, max_length=100)),
                ('SortOrder', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='CryptoassetVersionOne',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=100)),
                ('rank', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('rank', 'symbol'),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cryptoassets', models.ManyToManyField(to='apicc.Cryptoasset')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
