# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoassetversionone',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
