# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicc', '0003_auto_20170830_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cryptoassets',
            field=models.ManyToManyField(to='apicc.CryptoassetVersionOne'),
        ),
    ]
