# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicc', '0004_auto_20170830_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoassetversionone',
            options={'ordering': ('symbol',)},
        ),
    ]
