# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicc', '0005_auto_20170830_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('pname',)},
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='description',
            new_name='pdescription',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='name',
            new_name='pname',
        ),
    ]
